/// 接口: /system/ai/getAigConfigs
/// 方法: GET
/// 状态: 成功
/// code: 0
/// message: 操作成功

/// 响应数据:
/// ```json
{
  "code": 0,
  "message": "操作成功",
  "timestamp": 1775465271867,
  "data": [
    "Come over, I'll squeeze you dry",
    "aaaaaaaaaaaaaaaaaa! Yes?",
    "Come over, we'll have a blast",
    "Hobbies?",
    "Ahahahaah",
    "Feeling bored, wanna hang out?",
    "Experienced guys dig me.",
    "Bored??",
    "Boring",
    "Bored? Let's chill!",
    "Bored... wanna chat?",
    "Date here",
    "DDmm me",
    "Give me a chance, see what happens",
    "Home alone, so looking for a buddy",
    "Hai ...",
    "Halo!",
    "Hey, you new around here? Where you from?",
    "Heey ✋",
    "Heey there",
    "Hello baby",
    "Hello guys",
    "hello, how was your day?",
    "Hey there",
    "Hi",
    "Hi ?",
    "Hiee",
    "Hieee",
    "Hii",
    "Hlo",
    "Hook-up??",
    "Hotchat dm",
    "Hyy",
    "Hyyyyyyy",
    "Inbox Me",
    "tum yahan naya ho? chalo ek dusre ko jante hai",
    "Where are you from? North or south?",
    "Do you get ticklish?",
    "let's talk",
    "Wanna have some fun on call?",
    "talk to me",
    "Playboy job available in all India ❤️❤️❤️",
    "Ppp",
    "Sexting",
    "T e xt me",
    "Anyone who wants to have fun for free, come on over",
    ":) What are you doing?",
    "big brother wanna vc or not",
    "OMG, like, do you prefer being on top or underneath, babe? ?",
    "hungry boys here? M s g me?",
    "Any guy want to sex chat?",
    "Got time? Let's chat?",
    "There anybody need fun like online virtual fun , i am available here for virtual fun you can text me , and enjoy",
    "Anyone for just chat?",
    "Anyone horny now? Wanna sexting? Add me inbox",
    "Anyone want mastrubate",
    "I'm naked, just got out of the shower",
    "I'm in a bad mood today, can you lend me an ear?",
    "Will you take care of me, huh?",
    "Hey, I just noticed you. When do you usually hang out online?",
    "Just logged in. What about you?",
    "I’m new here hope am welcome",
    "Hey, I'm new here. Pleasure to meet you!",
    "Hey, I just spotted you. Relaxing?",
    "I'm bored, keep me company",
    "іm op ҽn fоr аnỵthḭng",
    "I need you",
    "I need a boyfriend",
    "I need a bf with a very big banana I can ride now",
    "I need a partner?‍❤️‍?‍?\nLoyal or introvert ?",
    "I need bed partner dm me",
    "Am I prettier than other girls here?",
    "Looking for a boyfriend, wanna be mine? ??",
    "I'm horny grill",
    "I don't want to be alone anymore, want to accompany me with a call?",
    "I accidentally saw you, can we get to know each other?",
    "I just finished showering, really want it, can you accompany me? ??",
    "I promise I'll help you cum",
    "Not often online. When do you usually come on?",
    "Ran into you here, feels like destiny, huh?",
    "I've been so annoyed lying on the bed all day, wanna VC to get to know each other?",
    "I'm at a hotel, let's meet up, I want it big.",
    "Hey babe, feeling kinda low. Can you cheer me up?",
    "Hey, seeking something serious. Are you into that too?",
    "Feeling a bit frisky, up for some fun? 轟",
    "iam very horny\nAdd me Horny \nboys cum together \nPlay for sexting class \nNo free,no time pass, please",
    "Hey, all by myself. Want to keep me company?",
    "ï m ỵοur nаughtỵ ρlɑỵmаtẹ",
    "I want to communicate with a man who is close to me. Sociable and open ?",
    "ï mеlt fσr ỵᴏu",
    "іm ɑlɭ уᴏurs, bɑby",
    "Curious to see your face. Ready when you are.",
    "Feeling hot and bothered, need to let off some steam.",
    "Hey, fancy a chat?",
    "ḭm crαvïng yӧu",
    "i want to touch you",
    "I wanna know a lot about you, tell me!",
    "I wanna know about you, do you wanna know about me?",
    "I've seen you before",
    "Feeling like we might vibe together, what do you think?",
    "Feeling a bit lonely, anyone up for a chat?",
    "Just chilling solo at home.",
    "Ready for a call, let's connect and have some fun!",
    "Hey, anyone up for a VC? my boyfriend's away, so it's just me here.",
    "Do I catch your eye? 馃槈",
    "Hey, how's it going? Up for a chat?",
    "How are you?",
    "What's your daily grind like?",
    "Newbie here, any tips?",
    "On the hunt for friends, maybe something more. ????",
    "ɭẹts gẹt hσt",
    "come on, chat with me",
    "Let's chat for a bit.",
    "Wanna have a chat?",
    "Come let's some naughty chats",
    "Let's call, I'm waiting for your call. ❤️?",
    "Let's chat, honey",
    "Help me cum horny sexting",
    "I just had a bath. What were you doing",
    "Just playing around, huh?",
    "brïng ӧut mỵ wḭɭd sїdẹ",
    "bеnd mе ovẹr",
    "Grateful for destiny for us to meet ❤️??",
    "mạк ҽ me quḭvеr, bɑby",
    "say something",
    "cɑn yσu hαndlҽ?",
    "Up for a chat?",
    "mаᏦё mе sсrёạm for morѐ",
    "drïve mѐ ϲrαzу",
    "Open for dating",
    "Sexy mommy wanna have some fun?",
    "Call me, I'll give you something special ???",
    "Cut girls dm msg pls",
    "Like what you see? ?",
    "If you're online, let's chat!",
    "let's get dirty,just now okay",
    "Hot boys come fast",
    "Horny young boys text me",
    "any playboy msg me for fun chat or voice call",
    "dҽеp ḭnsіde mѐ",
    "DM Something special here ?",
    "Dm me hurry up",
    "DM ME SEE what happens",
    "Dm my horny boys im not looking for relationship \nIm looking 4 have fun\nPaidd fun dm me",
    "How's your day today?",
    "How are you doing",
    "Wanna see me shake my pussy?",
    "free for various entertainment?",
    "I am 27 years old.. finding call girl / mistress for long term relationship.. Only pervert guy DM me for life partner..",
    "ïm α wiɭdcαt",
    "I'm new here",
    "I'm just from college I'm feeling a little horny if anyone wants to have sex with me inbox me",
    "I'm sitting alone, I'm bored I don't have enough attention",
    "I am so horny right now text me baby",
    "I am waiting bathroom",
    "I'm waiting bathroom",
    "I am looking for a soul mate DM me",
    "I feel alone guys let's have fun with me, text me inbox...... And free DM availab......",
    "I am alone in bathroom all opened",
    "I am alone in my house",
    "Im alone in my home",
    "Im alone in my home. Anyone interested ?",
    "I love vulgar communication I want to discuss an intimate experience. Open for new dialogues ?",
    "I am ready to chat with you dm me pls I am waiting for you",
    "Hey there, what's up?",
    "Hey babe, wanna know my secret? Call me, I'll give you something special.?",
    "hey baby what you up to ?? let's have a nice vc session ??",
    "Hi 30 yrs old divorced lady alone here.interested males dm me.",
    "Helo boys come online",
    "Hi guys message me",
    "Hello boys, I'm single girl. I'm here for fun and naughty chats, any real boy want secret fun please DM me.",
    "Hello handsome",
    "Hi am single girl and looking for good serious relationship? follow me genuine serious one",
    "Hi available",
    "Hey, got a moment to chat?",
    "Hey, just joined this app 'how's it going?",
    "Hello I’m available ???",
    "Hey, you new here? Looking for friends?",
    "Hey, you busy or what?",
    "Hi there, up for a video call?",
    "Hi single and searching",
    "hey handsome, you online? wanna vc? can you?",
    "Hey, wanna chat?",
    "Hey, big bro... what you up to? Wanna VC?",
    "Hlo guys I'm alvailble",
    "Hey sweetie, I'll treat you like royalty, give me a call now.",
    "hello my dear, my name is caroline. I am single and i would like to see and show with cam. if you have a coins, call me. You don't forget very well, thank you very munch for talking about me.Big kiss",
    "Hey! Here for some good company. DM",
    "Hello! You online now? Hit me up for a chat",
    "Hello, feeling a bit bored here.",
    "Hey there,happy to see you",
    "Hello, let's have some fun",
    "Hello, could you call me a few minutes",
    "Hey, do you like this?",
    "Hello, what should I call you?",
    "Hello, wow. I'm new here. How about you?",
    "Hellooo",
    "nɑughtу thоughts σnɭу",
    "Only for today Biggest Offer",
    "hey baby wanna vc? I'm alone here ?",
    "hey contact me",
    "Hey guys, hurry up, waiting in the bathroom, quick text me",
    "Hey guys, come quick, text me",
    "Hey im horny",
    "Hey brother, can I have a little time, if possible let's call",
    "Hey guys\nAvailable For Fun Only \nCommon Boys Text me Fast\nOnly Virtual Fun No Time Pass",
    "heyyyyyyyyyyyyyyyyy",
    "Hi babe, can I ask how long you can last?",
    "hi love, I'm already wet I have something to show you that you will love",
    "hi babe call me if u need md",
    "Hi, how are you?",
    "Hi, Hello uuuuuuuuuuuuu",
    "Hi,do you want a gril for sexy chat?",
    "Hi, wanna chat?",
    "hiiiiiiiiiiii",
    "avoid loneliness, love me",
    "Hookup Available",
    "Hey guys, hit me up",
    "Hyy guys massage me fast",
    "Hyyy guys massage me fast",
    "follow me Horny ??",
    "bѐ mỵ fạ ntasỵ",
    "bҽ mỵ sҽduϲеr",
    "bѐ mу guïɭtỵ рlẹạsure",
    "bҽ my dïrtỵ lïttɭe sѐcrѐt",
    "mаḳҽ mе yȯurs",
    "Please don't ignore me",
    "dont hσld bасᏦ",
    "if bro is okay with it lol",
    "If anyone really interested in secret stuff then try me one time?\nI promise you you don't need to go anywhere...??",
    "If you chat with me, I'll reply",
    "If you're bored, just chat with me",
    "If you want to know about me, just chat",
    "What are you doing? busy now?",
    "where are you from?",
    "You new here or what?",
    "Are you new here ? Can we VC",
    "Are you really just looking for friends here?",
    "What's your usual deal?",
    "What time are you usually online?",
    "What time do you usually get off work?",
    "You usually busy with work or what?",
    "can you see my msgs?",
    "Think you can help me out?",
    "Are you bored? I'm bored.",
    "Do you come every day? I want to talk to you",
    "are you here for fun?",
    "When you usually online?",
    "Are you free?",
    "What are you up to? Chat with me.",
    "Are you busy right now?",
    "Are you busy? Can we talk?",
    "are you up for it?",
    "Will you do sext with me?\nIam horny u? Add me \nNeed fun together \nHelp me cum\nNo free, No time pass, please",
    "are you online every day?",
    "Do you think I'm your type?",
    "Do you think my voice is sexy?",
    "Do you have a nickname?",
    "Do you have time to talk?",
    "Do you have time to chat with me all day?",
    "are you alone?",
    "Do you often come here?",
    "Do you use this app often?",
    "Are you single now?",
    "Do you like my profile picture?",
    "How long you been around? Am I the first one to hit you up?",
    "are you married?",
    "come here on",
    "Can we chat?",
    "Can we do three rounds, honey?",
    "Busy?",
    "F4m stoned looking 4 daddy",
    "brеɑk аll thҽ rulёs",
    "Sarvise available now",
    "unlеạsh thё bẹast",
    "unɭёạsh ỵσur dеsіrẹs",
    "pɭɑy wïth me",
    "Let's use a dildo when we video call, okay?",
    "Hey buddy, awake or catching some Z's? Hit me up, I'm bored here.",
    "Hey love, looking for a chat buddy tonight. Up for a video call? Just a sec!",
    "lҽts mɑке spɑrκs fɭy",
    "ɭёts bҽ sinfuɭ",
    "ɭёts gẹt nаughtỵ",
    "How about we make each other feel amazing, darling? ??",
    "ɭѐts ṗlạỵ dїrtỵ",
    "Want to get to know each other better? Just call",
    "Do you want to watch me finger myself with 3 fingers?",
    "Wanna see my pink pussy?",
    "wanna talking with guys , xoxo",
    "Wana talk with me",
    "wanna chat?",
    "Want, want, want.",
    "Honey Model",
    "Could you do me a favor? I'm sure you get what I'm saying, hehe",
    "Need sext start",
    "Ꭵnsatïạbɭё aррetitẹ, darɭïng",
    "Will you reply to my messages?",
    "It's boring. Let's chat.",
    "Hit me up for a chat",
    "Speak with me",
    "Chat me up babe",
    "Full enjoy full nude fingers",
    "Looking for a guy to chat with, no six plzzz",
    "hοttѐr, hоttѐr, hᴏttеr",
    "wanna see my d**do bby",
    "Message me boys ?",
    "Message me azap",
    "Messaged me",
    "Pm me naughty boy ?",
    "tạstѐ mѐ slowlу",
    "I'm single, you?",
    "Baby call me,full.open show",
    "Baby, I dey in the mood for some good loving. You fit satisfy me?",
    "Babe. I want to find a partner here. Shall we VC?",
    "Darling, let's vc, I'm home and free now, do you want have some fun?",
    "Hey babe, how's your body feeling? I wanna do things together that'll make us feel like we're in heaven.",
    "Honey, do you have work today? Let's video chat!!",
    "Nice too meet you guys I guess",
    "ṗleαsurе mѐ nоw",
    "S e x me or noo",
    "show me naked baby come see",
    "Who wants to meet",
    "Who wanna chat?",
    "What are you busy with? Let's chat",
    "Text me.. Am waiting",
    "msg me for secret fun and friendship",
    "Text Me For Fun I am available now",
    "sеduϲtivѐ ѐỵҽ s, bạby",
    "k ѐep mѐ wаntḭng mᴏre",
    "Today offer come to MSG me",
    "Tax me usa Boy",
    "call me show",
    "Pls msg me man",
    "Please call me. I'm going crazy ..",
    "tαkё ϲontrοɭ, hσnёy",
    "tаkе ït σff",
    "tаᏦѐ mẹ to nёw hẹïghts",
    "Already ready to go, give me some ??",
    "VC me you okay ?",
    "VC and sexting OK?",
    "You will be satisfied naked guaranteed",
    "It's fun time dm",
    "Wanna play? Call me ❤️❤️",
    "xhi handsome how are you...can u call me ..",
    "Looking for someone with an 18cm? DM me ?",
    "Hey I've already unzipped my pants k",
    "yo any real guy here who are down to talk?",
    "κḭss me ρassᎥσnạtẹɭу",
    "? come on?❤️",
    "Alone and bored, wanna chat a bit?",
    "Alone, I want a hot call my love",
    "Anyone up for some fun?",
    "Busy now, my love?",
    "Are you going to put it in my backdoor, daddy? Tell me now.",
    "Are you on this app every day or what?",
    "Are you single?",
    "Baby, I want to show you something.",
    "Baby, let me show you everything on the call",
    "Baby, wanna have some fun?",
    "bb can you do some masturbating on video call with me",
    "Been lying on the bed all day, bored to death, wanna call to kill the boredom, huh?",
    "Bored, wanna chat?",
    "call me and I'll let you know every part of me",
    "call me and let's have some fun!!! I promise you'll love it!! let's talk and enjoy!!",
    "Call me and you won't regret it",
    "Call me baby let's play",
    "Call me daddy, I'll show you my favorite position?",
    "call me to see my melons",
    "Call us please, we promise you'll be happy",
    "come play with me you won't regret it",
    "Come tell me your fetishes, let's play",
    "crushing on you bb wanna have a wonderful night",
    "Darling, I'm so needy... what are you up to?",
    "Darling, what are you doing? I'm alone, call me...",
    "Do you like spicy stuff?",
    "Do you wanna chat to kill the boredom?",
    "Feeling really lonely now, can you talk to me for a bit?",
    "Fill my pussy with cum, baby.",
    "Fuck me with your wet pussy I'm gonna squeeze you tight daddy",
    "hello! I'm so bored, wanna VC with me?",
    "Hey babe",
    "Hey bb come cum with me",
    "Hey bb, come keep me company",
    "hey daddy talk to me please",
    "hey moh, you know I love to masturbate on camera..",
    "Hey, I think we should get to know each other, don't you think?",
    "Hey, I wanna feel your hot thing inside me a little bit",
    "Hey, let me sit on your face and suffocate you with my pussy.",
    "hi sweetheart",
    "Hi there!",
    "Hi! I'm a new DJ here, can you call me?",
    "Hola bb, do you have something hard?",
    "Hola love, I'd love to get a call from you! I'll leave you satisfied..❤️‍ ❤️‍",
    "Hola love, I'm already wet",
    "Hola, are you free now?",
    "Hola. darling",
    "Honey, could you call me? I'm so bored.",
    "Honey, wanna video call with me? I'm so bored.",
    "I have something to show you, you'll love it.",
    "I want milk and the single gave me a shower, baby.",
    "I'm feeling depressed lying in bed all day. Can we be friends via video call?",
    "I'm in the shower, call me if you wanna see.",
    "I'm very bored, alone.",
    "I'm very lonely",
    "Just finished bathing, what are you doing?",
    "Let's get rid of boredom together, love. How about calling me? Call me",
    "Let's have a chat, darling.",
    "Let's introduce ourselves, okay?",
    "love talk to me I'm naughty lol",
    "Man, you look familiar, been on this app for ages or what?",
    "My angel, call me, you'll go crazy for me",
    "Nice to meet you",
    "Oi, I'm imagining your size...",
    "Online, baby!",
    "Seeing you, my body automatically ignites. come help me!",
    "Someone talk to me please",
    "Soy una chica seria y quiero un hombre en serio",
    "Stick it in my wet pussy, I want to feel you, baby.",
    "Stuck at home all day, so bored and lonely. Anyone up for a call?",
    "Suck it deliciously with me amore",
    "Want to see my big boobs and hairy pussy? Call me!",
    "Where are you at?",
    "You new here? Wanna hop on video calls or what?",
    "Your pussy looks so wet, baby",
    "Yummy, call me and I promise you won't regret it."
  ]
}
/// ```
