/// 接口: /p/product/getProductsWithCoupon
/// 方法: GET
/// 状态: 成功
/// code: 0
/// message: 操作成功

/// 响应数据:
/// ```json
{
  "code": 0,
  "message": "操作成功",
  "timestamp": 1775465294272,
  "data": [
    {
      "productId": 1825479644239925250,
      "productCode": "sela499",
      "price": 499,
      "diamonds": 800000,
      "bonus": 10000,
      "vipDays": 1,
      "callCardNum": 3,
      "matchCardNum": 4,
      "chatCardNum": 5,
      "productType": 2,
      "discountType": 4,
      "discount": 10,
      "productOrder": 1,
      "vipUnitPrice": 499,
      "currencyPrice": 499,
      "currencyCode": "USD",
      "splits": [
        {
          "splitDay": 1,
          "diamonds": 100000,
          "bonus": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "splitDay": 2,
          "diamonds": 200000,
          "bonus": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "splitDay": 3,
          "diamonds": 500000,
          "bonus": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        }
      ],
      "ppp": [
        {
          "ppId": 1,
          "ppType": 1,
          "ccType": null,
          "ccName": "Google",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/2a8e661418051e3b3d1d76002fe302b1.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 499,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 2039259293217206274,
          "ppType": 23,
          "ccType": "",
          "ccName": "cashApp",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/632904490de19d9cf96316d3bf135fe6.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 499,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1972914931478720514,
          "ppType": 19,
          "ccType": "card",
          "ccName": "Credit Card_pdd",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 499,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1980186127223963650,
          "ppType": 22,
          "ccType": "card",
          "ccName": "Credit Card_pdd2",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 499,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        }
      ],
      "coupons": []
    },
    {
      "productId": 1931919820150439938,
      "productCode": "sela169",
      "price": 169,
      "diamonds": 120000,
      "bonus": 30000,
      "vipDays": 0,
      "callCardNum": 0,
      "matchCardNum": 0,
      "chatCardNum": 0,
      "productType": 1,
      "discountType": null,
      "discount": null,
      "productOrder": 1,
      "vipUnitPrice": 0,
      "currencyPrice": 169,
      "currencyCode": "USD",
      "splits": [],
      "ppp": [
        {
          "ppId": 1,
          "ppType": 1,
          "ccType": null,
          "ccName": "Google",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/2a8e661418051e3b3d1d76002fe302b1.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 169,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 2039259293217206274,
          "ppType": 23,
          "ccType": "",
          "ccName": "cashApp",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/632904490de19d9cf96316d3bf135fe6.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 169,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1972914931478720514,
          "ppType": 19,
          "ccType": "card",
          "ccName": "Credit Card_pdd",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 169,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1980186127223963650,
          "ppType": 22,
          "ccType": "card",
          "ccName": "Credit Card_pdd2",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 169,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        }
      ],
      "coupons": []
    },
    {
      "productId": 1784515573785423873,
      "productCode": "sela99",
      "price": 99,
      "diamonds": 200000,
      "bonus": 100000,
      "vipDays": 3,
      "callCardNum": 1,
      "matchCardNum": 1,
      "chatCardNum": 1,
      "productType": 1,
      "discountType": null,
      "discount": 5,
      "productOrder": 2,
      "vipUnitPrice": 33,
      "currencyPrice": 99,
      "currencyCode": "USD",
      "splits": [],
      "ppp": [
        {
          "ppId": 1,
          "ppType": 1,
          "ccType": null,
          "ccName": "Google",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/2a8e661418051e3b3d1d76002fe302b1.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 99,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 2039259293217206274,
          "ppType": 23,
          "ccType": "",
          "ccName": "cashApp",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/632904490de19d9cf96316d3bf135fe6.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 99,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1972914931478720514,
          "ppType": 19,
          "ccType": "card",
          "ccName": "Credit Card_pdd",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 99,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1980186127223963650,
          "ppType": 22,
          "ccType": "card",
          "ccName": "Credit Card_pdd2",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 99,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        }
      ],
      "coupons": []
    },
    {
      "productId": 2,
      "productCode": "sela599",
      "price": 599,
      "diamonds": 900000,
      "bonus": 30000,
      "vipDays": 3,
      "callCardNum": 1,
      "matchCardNum": 1,
      "chatCardNum": 1,
      "productType": 1,
      "discountType": null,
      "discount": 20,
      "productOrder": 3,
      "vipUnitPrice": 199,
      "currencyPrice": 599,
      "currencyCode": "USD",
      "splits": [],
      "ppp": [
        {
          "ppId": 1,
          "ppType": 1,
          "ccType": null,
          "ccName": "Google",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/2a8e661418051e3b3d1d76002fe302b1.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 599,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 2039259293217206274,
          "ppType": 23,
          "ccType": "",
          "ccName": "cashApp",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/632904490de19d9cf96316d3bf135fe6.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 599,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1972914931478720514,
          "ppType": 19,
          "ccType": "card",
          "ccName": "Credit Card_pdd",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 599,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1980186127223963650,
          "ppType": 22,
          "ccType": "card",
          "ccName": "Credit Card_pdd2",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 599,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        }
      ],
      "coupons": []
    },
    {
      "productId": 3,
      "productCode": "sela999",
      "price": 999,
      "diamonds": 4000000,
      "bonus": 0,
      "vipDays": 3,
      "callCardNum": 0,
      "matchCardNum": 0,
      "chatCardNum": 0,
      "productType": 1,
      "discountType": null,
      "discount": 10,
      "productOrder": 4,
      "vipUnitPrice": 333,
      "currencyPrice": 999,
      "currencyCode": "USD",
      "splits": [],
      "ppp": [
        {
          "ppId": 1,
          "ppType": 1,
          "ccType": null,
          "ccName": "Google",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/2a8e661418051e3b3d1d76002fe302b1.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 999,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 2039259293217206274,
          "ppType": 23,
          "ccType": "",
          "ccName": "cashApp",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/632904490de19d9cf96316d3bf135fe6.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 999,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1972914931478720514,
          "ppType": 19,
          "ccType": "card",
          "ccName": "Credit Card_pdd",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 999,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1980186127223963650,
          "ppType": 22,
          "ccType": "card",
          "ccName": "Credit Card_pdd2",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 999,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        }
      ],
      "coupons": []
    },
    {
      "productId": 1788101865223790594,
      "productCode": "sela1699",
      "price": 1699,
      "diamonds": 100000000,
      "bonus": 0,
      "vipDays": 0,
      "callCardNum": 0,
      "matchCardNum": 0,
      "chatCardNum": 0,
      "productType": 1,
      "discountType": null,
      "discount": null,
      "productOrder": 6,
      "vipUnitPrice": 0,
      "currencyPrice": 1699,
      "currencyCode": "USD",
      "splits": [],
      "ppp": [
        {
          "ppId": 1,
          "ppType": 1,
          "ccType": null,
          "ccName": "Google",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/2a8e661418051e3b3d1d76002fe302b1.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 1699,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 2039259293217206274,
          "ppType": 23,
          "ccType": "",
          "ccName": "cashApp",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/632904490de19d9cf96316d3bf135fe6.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 1699,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1972914931478720514,
          "ppType": 19,
          "ccType": "card",
          "ccName": "Credit Card_pdd",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 1699,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1980186127223963650,
          "ppType": 22,
          "ccType": "card",
          "ccName": "Credit Card_pdd2",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 1699,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        }
      ],
      "coupons": []
    },
    {
      "productId": 1821804816689537026,
      "productCode": "sela9999",
      "price": 9999,
      "diamonds": 50000000,
      "bonus": 0,
      "vipDays": 0,
      "callCardNum": 0,
      "matchCardNum": 0,
      "chatCardNum": 0,
      "productType": 1,
      "discountType": null,
      "discount": null,
      "productOrder": 10,
      "vipUnitPrice": 0,
      "currencyPrice": 9999,
      "currencyCode": "USD",
      "splits": [],
      "ppp": [
        {
          "ppId": 1,
          "ppType": 1,
          "ccType": null,
          "ccName": "Google",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/2a8e661418051e3b3d1d76002fe302b1.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 9999,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 2039259293217206274,
          "ppType": 23,
          "ccType": "",
          "ccName": "cashApp",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/632904490de19d9cf96316d3bf135fe6.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 9999,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1972914931478720514,
          "ppType": 19,
          "ccType": "card",
          "ccName": "Credit Card_pdd",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 9999,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1980186127223963650,
          "ppType": 22,
          "ccType": "card",
          "ccName": "Credit Card_pdd2",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 9999,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        }
      ],
      "coupons": []
    },
    {
      "productId": 1846079896764284930,
      "productCode": "sela899",
      "price": 899,
      "diamonds": 1000000000,
      "bonus": 0,
      "vipDays": 0,
      "callCardNum": 0,
      "matchCardNum": 0,
      "chatCardNum": 0,
      "productType": 1,
      "discountType": null,
      "discount": null,
      "productOrder": 10,
      "vipUnitPrice": 0,
      "currencyPrice": 899,
      "currencyCode": "USD",
      "splits": [],
      "ppp": [
        {
          "ppId": 1,
          "ppType": 1,
          "ccType": null,
          "ccName": "Google",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/2a8e661418051e3b3d1d76002fe302b1.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 899,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 2039259293217206274,
          "ppType": 23,
          "ccType": "",
          "ccName": "cashApp",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/632904490de19d9cf96316d3bf135fe6.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 899,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1972914931478720514,
          "ppType": 19,
          "ccType": "card",
          "ccName": "Credit Card_pdd",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 899,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1980186127223963650,
          "ppType": 22,
          "ccType": "card",
          "ccName": "Credit Card_pdd2",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 899,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        }
      ],
      "coupons": []
    },
    {
      "productId": 1933348025520513026,
      "productCode": "sela799",
      "price": 799,
      "diamonds": 150000,
      "bonus": 50000,
      "vipDays": 0,
      "callCardNum": 0,
      "matchCardNum": 0,
      "chatCardNum": 0,
      "productType": 1,
      "discountType": null,
      "discount": null,
      "productOrder": 10,
      "vipUnitPrice": 0,
      "currencyPrice": 799,
      "currencyCode": "USD",
      "splits": [],
      "ppp": [
        {
          "ppId": 1,
          "ppType": 1,
          "ccType": null,
          "ccName": "Google",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/2a8e661418051e3b3d1d76002fe302b1.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 799,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 2039259293217206274,
          "ppType": 23,
          "ccType": "",
          "ccName": "cashApp",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/632904490de19d9cf96316d3bf135fe6.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 0,
          "ppOrder": 1,
          "browserOpen": 0,
          "currencyPrice": 799,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1972914931478720514,
          "ppType": 19,
          "ccType": "card",
          "ccName": "Credit Card_pdd",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 799,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        },
        {
          "ppId": 1980186127223963650,
          "ppType": 22,
          "ccType": "card",
          "ccName": "Credit Card_pdd2",
          "nationalFlagPath": "https://wss3.vipcallco.com/users/test/0/pay/891a4d4f0a576e2d5369f51008ca8fdd.png",
          "uploadUsd": 0,
          "supportCoupon": 0,
          "discountFlag": 1,
          "ppOrder": 2,
          "browserOpen": 0,
          "currencyPrice": 799,
          "currencyCode": "USD",
          "diamonds": 0,
          "vipDays": 0,
          "callCardNum": 0,
          "matchCardNum": 0,
          "chatCardNum": 0
        }
      ],
      "coupons": []
    }
  ]
}
/// ```
